#define T_CONST 1
#define T_INTEGER 2
#define T_BYTE 3
#define T_STRING 4
#define T_WHILE 5
#define T_IF 6
#define T_ELSE 7
#define T_AND 8
#define T_OR 9
#define T_NOT 10
#define T_ASSIGN 11
#define T_EQUALS 12
#define T_OPEN_PARENTESIS 13
#define T_CLOSE_PARENTESIS 14
#define T_LESSER_THAN 15
#define T_GREATER_THAN 16
#define T_NOT_EQUAL 17
#define T_GREATER_THAN_EQUAL 18
#define T_LESSER_THAN_EQUAL 19
#define T_COMMA 20
#define T_ADD 21
#define T_SUBTRACT 22
#define T_MULTIPLY 23 
#define T_DIVIDE 24
#define T_SEMICOLON 25
#define T_BEGIN 26
#define T_END 27
#define T_THEN 28
#define T_READLN 29
#define T_WRITE 30
#define T_WRITELN 31
#define T_MAIN 32
#define T_BOOLEAN 33
#define T_TRUE 34
#define T_FALSE 34
#define T_STRING_LITERAL 34
#define T_VALUE 34
#define T_ID 35

#define T_NEW_ID 101

#define INVALID_CHAR 503
#define UNEXPECTED_EOF 502
#define EOF_NO_LEX 501
#define LEX_ERROR 500